jar {
    archiveFileName = "Mystcraft Legacy - ${version} - Fabric-dev.jar"
}

remapJar {
    archiveFileName = "Mystcraft Legacy - ${version} - Fabric.jar"
}

sourcesJar {
    archiveFileName = "Mystcraft Legacy - ${version} - Fabric-sources-dev.jar"
}

remapSourcesJar {
    archiveFileName = "Mystcraft Legacy - ${version} - Fabric-sources.jar"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly project(':common')
}
