dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    compileOnly project(':common')
    annotationProcessor("org.spongepowered:mixin:0.8.5:processor")
}

tasks.named('compileJava', JavaCompile) {
    source(project(':common').sourceSets.main.allSource)
}

tasks.named('processResources', ProcessResources) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(':common').sourceSets.main.resources
}

tasks.named('sourcesJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(':common').sourceSets.main.allSource
    from project(':common').sourceSets.main.resources
}

jar.finalizedBy('reobfJar')
