# Gradle Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

# Minecraft/Forge Versions
minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.21)
forge_version=48.1.0
forge_version_range=[48,)
loader_version_range=[48,)

# Mappings - using official Mojang mappings - Need to change later...
mapping_channel=official
mapping_version=1.20.2

# Mod Properties
mod_id=mystcraft
mod_name=Mystcraft Legacy - Pages Returned
mod_license=LGPLv3
mod_version=1.0.0
mod_group_id=art.arcane.mystcraft
mod_authors=NextdoorPsycho
mod_description=Mystcraft Legacy - Pages Returned, is my continuation of the Mystcraft mod for Minecraft 1.20.2 and beyond. This was Written From Scratched, and the fork for the repo was merely for Creative Direction, Assets have been retained but for now will be placeholders until i can get approval to use them, or create my own.

# Optional: Note to future self: Parchment mappings for better parameter names (uncomment to use)
# mapping_channel=parchment
# mapping_version=2023.12.31-1.20.2
# parchment_minecraft_version=1.20.2
