pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = uri('https://maven.fabricmc.net')
        }
        maven {
            name = 'Sponge'
            url = uri('https://repo.spongepowered.org/repository/maven-public')
        }
        maven {
            name = 'Forge'
            url = uri('https://maven.minecraftforge.net')
        }
    }
}

plugins {
    // Foojay Toolchains Plugin - automatically downloads/provisions correct JDK versions
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = 'Minecraft Libraries'
            url = uri('https://libraries.minecraft.net')
            content {
                includeGroup 'org.lwjgl'
            }
        }
        mavenCentral {
            content {
                excludeGroup 'org.lwjgl'
            }
        }
        maven {
            name = 'Fabric'
            url = uri('https://maven.fabricmc.net')
        }
        maven {
            name = 'Sponge'
            url = uri('https://repo.spongepowered.org/repository/maven-public')
        }
        maven {
            name = 'Forge'
            url = uri('https://maven.minecraftforge.net')
        }
    }
}

rootProject.name = 'Mystcraft'
include('common')
include('fabric:1.20.1')
include('forge:1.20.1')
