buildscript {
    repositories {
        maven { url = 'https://maven.neoforged.net/releases' }
        gradlePluginPortal()
    }
    dependencies {
        classpath "net.neoforged.gradle:userdev:7.0.41"
    }
}

apply plugin: 'net.neoforged.gradle.userdev'

apply from: 'gradle/base.gradle'

apply from: 'gradle/minecraft.gradle'
apply from: 'gradle/run-base.gradle'
apply from: 'gradle/run-client.gradle'
apply from: 'gradle/run-server.gradle'
apply from: 'gradle/run-data.gradle'

apply from: 'gradle/sources.gradle'
apply from: 'gradle/tasks.gradle'
