package art.arcane.mystcraft.block;

import art.arcane.mystcraft.Mystcraft;
import art.arcane.mystcraft.blockentity.BookReceptacleBlockEntity;
import art.arcane.mystcraft.blockentity.LinkPortalBlockEntity;
import art.arcane.mystcraft.data.LinkFlags;
import art.arcane.mystcraft.data.LinkOptions;
import art.arcane.mystcraft.item.AgebookItem;
import art.arcane.mystcraft.item.LinkbookItem;
import art.arcane.mystcraft.item.PersonalLinkBookItem;
import art.arcane.mystcraft.link.LinkingManager;
import art.arcane.mystcraft.portal.PortalUtils;
import art.arcane.mystcraft.registry.ModSounds;
import art.arcane.mystcraft.util.ItemStackNbt;
import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.InsideBlockEffectApplier;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.BaseEntityBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RenderShape;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.level.redstone.Orientation;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.jetbrains.annotations.Nullable;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The Link Portal block — the teleportation surface inside a Mystcraft portal.
 * <p>
 * Generated by {@link PortalUtils} when a Book Receptacle is activated. The
 * portal block is a thin slab whose orientation is determined by the
 * {@link #AXIS} property:
 * <ul>
 *   <li>{@code AXIS=X}: portal plane is YZ, walked through traveling east/west.</li>
 *   <li>{@code AXIS=Y}: portal plane is XZ (a horizontal portal you fall through).</li>
 *   <li>{@code AXIS=Z}: portal plane is XY, walked through traveling north/south.</li>
 * </ul>
 * The axis is set at creation time from the receptacle's facing axis — there is
 * no separate "pointer back" direction; teleport-side receptacle discovery is
 * done with a BFS through connected portal/crystal blocks.
 */
public class LinkPortalBlock extends BaseEntityBlock {

  public static final EnumProperty<Direction.Axis> AXIS = BlockStateProperties.AXIS;
  public static final MapCodec<LinkPortalBlock> CODEC = simpleCodec(LinkPortalBlock::new);

  // Per-(entity, portal-block) cooldowns. Keying by both prevents the
  // "walk through one portal, then back through a different one" path from
  // being silently swallowed because the player's UUID is on global
  // cooldown. Pruned periodically.
  private static final Map<UUID, Map<PortalLocation, Long>> TELEPORT_COOLDOWNS = new HashMap<>();
  private static final long COOLDOWN_TICKS = 100;
  private static final int COOLDOWN_PRUNE_THRESHOLD = 256;

  public LinkPortalBlock(Properties properties) {
    super(properties);
    registerDefaultState(stateDefinition.any().setValue(AXIS, Direction.Axis.Y));
  }

  @Override
  protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
    builder.add(AXIS);
  }

  protected MapCodec<? extends BaseEntityBlock> codec() {
    return CODEC;
  }

  @Nullable
  @Override
  public BlockEntity newBlockEntity(BlockPos pos, BlockState state) {
    return new LinkPortalBlockEntity(pos, state);
  }

  /**
   * Portal blocks render as solid (the texture is drawn by the block model),
   * not the default INVISIBLE that {@link BaseEntityBlock} uses for blocks
   * with custom BE-driven rendering. The BE here only stores data; rendering
   * still uses the standard model pipeline.
   */
  @Override
  public RenderShape getRenderShape(BlockState state) {
    return RenderShape.MODEL;
  }

  /**
   * Outline shape used for raycasts; matches the visible slab geometry.
   */
  @Override
  public VoxelShape getShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return switch (state.getValue(AXIS)) {
      case X -> Block.box(6, 0, 0, 10, 16, 16);
      case Y -> Block.box(0, 6, 0, 16, 10, 16);
      case Z -> Block.box(0, 0, 6, 16, 16, 10);
    };
  }

  /**
   * Portals are pass-through — entities walk into them.
   */
  @Override
  public VoxelShape getCollisionShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return Shapes.empty();
  }

  @Override
  public VoxelShape getVisualShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return Shapes.empty();
  }

  /**
   * Mirror/rotate handling so structure rotations keep the axis consistent.
   */
  @Override
  public BlockState rotate(BlockState state, net.minecraft.world.level.block.Rotation rotation) {
    return switch (rotation) {
      case COUNTERCLOCKWISE_90, CLOCKWISE_90 -> switch (state.getValue(AXIS)) {
        case X -> state.setValue(AXIS, Direction.Axis.Z);
        case Z -> state.setValue(AXIS, Direction.Axis.X);
        default -> state;
      };
      default -> state;
    };
  }

  @Override
  protected void entityInside(BlockState state, Level level, BlockPos pos, Entity entity,
                              InsideBlockEffectApplier effectApplier, boolean isPrecise) {
    if (level.isClientSide()) {
      return;
    }

    long currentTime = level.getGameTime();
    if (isOnCooldown(entity, level.dimension(), pos, currentTime)) {
      return;
    }

    BookReceptacleBlockEntity receptacle = findReceptacle(level, pos);
    if (receptacle == null || !receptacle.hasBook()) {

      return;
    }

    ItemStack book = receptacle.getBook();

    if (book.getItem() instanceof PersonalLinkBookItem personalBook
        && entity instanceof ServerPlayer) {
      setCooldown(entity, level.dimension(), pos, currentTime);
      level.playSound(null, pos, ModSounds.LINKING_PORTAL.get(), SoundSource.BLOCKS, 1.0f, 1.0f);
      personalBook.activate(book, level, entity);
      return;
    }

    if (book.getItem() instanceof AgebookItem agebookItem
        && LinkOptions.getDimensionUID(ItemStackNbt.getTag(book)) == null
        && entity instanceof ServerPlayer serverPlayer) {
      agebookItem.activate(book, level, entity);
      if (LinkOptions.getDimensionUID(ItemStackNbt.getTag(book)) == null) {

        art.arcane.mystcraft.util.PlayerMessages.send(serverPlayer,
            Component.translatable("mystcraft.portal.agebook_no_link_panel"), true);
        return;
      }
      art.arcane.mystcraft.util.PlayerMessages.send(serverPlayer,
          Component.translatable("mystcraft.portal.agebook_age_created"), true);
      setCooldown(entity, level.dimension(), pos, currentTime);
      return;
    }

    CompoundTag linkData = getLinkData(book);
    if (linkData == null) {
      return;
    }

    setCooldown(entity, level.dimension(), pos, currentTime);

    level.playSound(null, pos, ModSounds.LINKING_PORTAL.get(), SoundSource.BLOCKS, 1.0f, 1.0f);

    CompoundTag portalLinkData = linkData.copy();
    LinkOptions.setFlag(portalLinkData, LinkFlags.MAINTAIN_MOMENTUM, true);
    LinkOptions.setFlag(portalLinkData, LinkFlags.GENERATE_PLATFORM, false);
    LinkOptions.setSpawnYaw(portalLinkData, entity.getYRot());

    LinkingManager.LinkResult result = LinkingManager.performLink(entity, portalLinkData);

    if (result != LinkingManager.LinkResult.SUCCESS) {
      Mystcraft.LOGGER.warn("[Portal] Link failed at {}: {}", pos, result);
      if (entity instanceof ServerPlayer player) {
        art.arcane.mystcraft.util.PlayerMessages.send(player,
            Component.translatable("mystcraft.portal.link_failed", result.name()),
            true);
      }
    }

    if (currentTime % 1200 == 0) {
      pruneCooldowns(currentTime);
    }
  }

  private static boolean isOnCooldown(Entity entity, ResourceKey<Level> dimension,
                                      BlockPos portalBlockPos, long now) {
    Map<PortalLocation, Long> perEntity = TELEPORT_COOLDOWNS.get(entity.getUUID());
    if (perEntity == null) {
      return false;
    }
    Long last = perEntity.get(new PortalLocation(dimension, portalBlockPos));
    return isActiveCooldown(last, now);
  }

  private static void setCooldown(Entity entity, ResourceKey<Level> dimension,
                                  BlockPos portalBlockPos, long now) {
    TELEPORT_COOLDOWNS
        .computeIfAbsent(entity.getUUID(), k -> new HashMap<>())
        .put(new PortalLocation(dimension, portalBlockPos), now);
    if (TELEPORT_COOLDOWNS.size() > COOLDOWN_PRUNE_THRESHOLD) {
      pruneCooldowns(now);
    }
  }

  private static void pruneCooldowns(long now) {
    long stale = COOLDOWN_TICKS * 2;
    TELEPORT_COOLDOWNS.values().forEach(perEntity ->
        perEntity.entrySet().removeIf(e -> now - e.getValue() < 0 || now - e.getValue() > stale));
    TELEPORT_COOLDOWNS.entrySet().removeIf(e -> e.getValue().isEmpty());
  }

  // ---------------------------------------------------------------------------
  // Test-only hooks for the gametest harness. The cooldown map is a static
  // {@code Map<UUID, Map<PortalLocation,Long>>} that lets us prove the per-portal
  // keying (Phase 2.5) without standing up a real ServerPlayer in two
  // dimensions. Production code must NEVER call these.
  // ---------------------------------------------------------------------------
  public static void clearCooldownsForTest() {
    TELEPORT_COOLDOWNS.clear();
  }

  public static void setCooldownForTest(UUID id, BlockPos portalBlockPos, long now) {
    setCooldownForTest(id, Level.OVERWORLD, portalBlockPos, now);
  }

  public static void setCooldownForTest(UUID id, ResourceKey<Level> dimension,
                                        BlockPos portalBlockPos, long now) {
    TELEPORT_COOLDOWNS
        .computeIfAbsent(id, k -> new HashMap<>())
        .put(new PortalLocation(dimension, portalBlockPos), now);
  }

  public static boolean isOnCooldownForTest(UUID id, BlockPos portalBlockPos, long now) {
    return isOnCooldownForTest(id, Level.OVERWORLD, portalBlockPos, now);
  }

  public static boolean isOnCooldownForTest(UUID id, ResourceKey<Level> dimension,
                                             BlockPos portalBlockPos, long now) {
    Map<PortalLocation, Long> perEntity = TELEPORT_COOLDOWNS.get(id);
    if (perEntity == null) {
      return false;
    }
    Long last = perEntity.get(new PortalLocation(dimension, portalBlockPos));
    return isActiveCooldown(last, now);
  }

  private static boolean isActiveCooldown(@Nullable Long last, long now) {
    if (last == null) {
      return false;
    }
    long elapsed = now - last;
    return elapsed >= 0 && elapsed < COOLDOWN_TICKS;
  }

  public static long cooldownTicksForTest() {
    return COOLDOWN_TICKS;
  }

  private record PortalLocation(ResourceKey<Level> dimension, BlockPos blockPos) {
    private PortalLocation {
      blockPos = blockPos.immutable();
    }
  }

  private CompoundTag getLinkData(ItemStack book) {
    if (book.isEmpty() || ItemStackNbt.getTag(book) == null) {
      return null;
    }
    if (book.getItem() instanceof LinkbookItem || book.getItem() instanceof AgebookItem) {
      return ItemStackNbt.getTag(book);
    }
    return null;
  }

  private BookReceptacleBlockEntity findReceptacle(Level level, BlockPos pos) {
    // BE-fast path: every v2 portal cell stamps its receptacle pointer at
    // fire time. Avoid the structure BFS unless the BE has no pointer
    // (pre-v2 saved worlds, manual /setblock placements, or stale portal
    // cells from a partial teardown).
    if (level.getBlockEntity(pos) instanceof LinkPortalBlockEntity portalBE) {
      BlockPos rp = portalBE.getReceptaclePos();
      if (rp != null
          && level.getBlockEntity(rp) instanceof BookReceptacleBlockEntity recBE) {
        return recBE;
      }
    }
    if (PortalUtils.findReceptacle(level, pos) instanceof BookReceptacleBlockEntity receptacle) {
      return receptacle;
    }
    return null;
  }

  @Override
  protected void neighborChanged(BlockState state, Level level, BlockPos pos, Block neighborBlock,
                                 Orientation orientation, boolean movedByPiston) {
    if (level.isClientSide()) return;
    // BE-pointer-driven validation: O(1) receptacle lookup and a hasBook()
    // check. The legacy {@link PortalUtils#validatePortal} BFS is still
    // available as the fallback for pre-v2 portal cells; new portals never
    // hit it.
    PortalUtils.maybeShutdownIfOrphaned(level, pos);
  }
}
