package art.arcane.mystcraft.block;

import art.arcane.mystcraft.Mystcraft;
import art.arcane.mystcraft.blockentity.BookReceptacleBlockEntity;
import art.arcane.mystcraft.data.LinkFlags;
import art.arcane.mystcraft.data.LinkOptions;
import art.arcane.mystcraft.item.AgebookItem;
import art.arcane.mystcraft.item.LinkbookItem;
import art.arcane.mystcraft.link.LinkingManager;
import art.arcane.mystcraft.portal.PortalUtils;
import art.arcane.mystcraft.registry.ModSounds;
import art.arcane.mystcraft.util.ItemStackNbt;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The Link Portal block — the teleportation surface inside a Mystcraft portal.
 * <p>
 * Generated by {@link PortalUtils} when a Book Receptacle is activated. The
 * portal block is a thin slab whose orientation is determined by the
 * {@link #AXIS} property:
 * <ul>
 *   <li>{@code AXIS=X}: portal plane is YZ, walked through traveling east/west.</li>
 *   <li>{@code AXIS=Y}: portal plane is XZ (a horizontal portal you fall through).</li>
 *   <li>{@code AXIS=Z}: portal plane is XY, walked through traveling north/south.</li>
 * </ul>
 * The axis is set at creation time from the receptacle's facing axis — there is
 * no separate "pointer back" direction; teleport-side receptacle discovery is
 * done with a BFS through connected portal/crystal blocks.
 */
public class LinkPortalBlock extends Block {

  public static final EnumProperty<Direction.Axis> AXIS = BlockStateProperties.AXIS;

  // Cooldown to prevent spam teleporting (entity UUID -> last teleport time)
  private static final Map<UUID, Long> TELEPORT_COOLDOWNS = new HashMap<>();
  private static final long COOLDOWN_TICKS = 100; // 5 seconds

  public LinkPortalBlock(Properties properties) {
    super(properties);
    registerDefaultState(stateDefinition.any().setValue(AXIS, Direction.Axis.Y));
  }

  @Override
  protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
    builder.add(AXIS);
  }

  /**
   * Outline shape used for raycasts; matches the visible slab geometry.
   */
  @Override
  public VoxelShape getShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return switch (state.getValue(AXIS)) {
      case X -> Block.box(6, 0, 0, 10, 16, 16);
      case Y -> Block.box(0, 6, 0, 16, 10, 16);
      case Z -> Block.box(0, 0, 6, 16, 16, 10);
    };
  }

  /**
   * Portals are pass-through — entities walk into them.
   */
  @Override
  public VoxelShape getCollisionShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return Shapes.empty();
  }

  @Override
  public VoxelShape getVisualShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
    return Shapes.empty();
  }

  /**
   * Mirror/rotate handling so structure rotations keep the axis consistent.
   */
  @Override
  public BlockState rotate(BlockState state, net.minecraft.world.level.block.Rotation rotation) {
    return switch (rotation) {
      case COUNTERCLOCKWISE_90, CLOCKWISE_90 -> switch (state.getValue(AXIS)) {
        case X -> state.setValue(AXIS, Direction.Axis.Z);
        case Z -> state.setValue(AXIS, Direction.Axis.X);
        default -> state;
      };
      default -> state;
    };
  }

  @Override
  public void entityInside(BlockState state, Level level, BlockPos pos, Entity entity) {
    if (level.isClientSide) {
      return;
    }

    UUID entityId = entity.getUUID();
    long currentTime = level.getGameTime();
    Long lastTeleport = TELEPORT_COOLDOWNS.get(entityId);
    if (lastTeleport != null && currentTime - lastTeleport < COOLDOWN_TICKS) {
      return; // Still in cooldown
    }

    BookReceptacleBlockEntity receptacle = findReceptacle(level, pos);
    if (receptacle == null || !receptacle.hasBook()) {
      // Frame validation is handled in neighborChanged + PortalUtils.validatePortal.
      // Don't tear blocks down on contact — that cascades into a destroyed portal.
      return;
    }

    ItemStack book = receptacle.getBook();

    // Activate brand-new Agebook on first contact (matches legacy behavior:
    // place book → walk through → Age created).
    if (book.getItem() instanceof AgebookItem agebookItem
        && LinkOptions.getDimensionUID(ItemStackNbt.getTag(book)) == null
        && entity instanceof ServerPlayer) {
      agebookItem.activate(book, level, entity);
      if (LinkOptions.getDimensionUID(ItemStackNbt.getTag(book)) == null) {
        return; // Activation failed (e.g., missing link panel)
      }
      TELEPORT_COOLDOWNS.put(entityId, currentTime);
      return;
    }

    CompoundTag linkData = getLinkData(book);
    if (linkData == null) {
      return;
    }

    TELEPORT_COOLDOWNS.put(entityId, currentTime);

    level.playSound(null, pos, ModSounds.LINKING_PORTAL.get(), SoundSource.BLOCKS, 1.0f, 1.0f);

    // Apply portal-specific flag overrides without mutating the source book.
    CompoundTag portalLinkData = linkData.copy();
    LinkOptions.setFlag(portalLinkData, LinkFlags.MAINTAIN_MOMENTUM, true);
    LinkOptions.setFlag(portalLinkData, LinkFlags.GENERATE_PLATFORM, false);

    LinkingManager.LinkResult result = LinkingManager.performLink(entity, portalLinkData);

    if (result != LinkingManager.LinkResult.SUCCESS) {
      Mystcraft.LOGGER.warn("[Portal] Link failed at {}: {}", pos, result);
      if (entity instanceof ServerPlayer player) {
        player.displayClientMessage(
            net.minecraft.network.chat.Component.translatable("mystcraft.portal.link_failed", result.name()),
            true);
      }
    }

    // Periodically prune stale cooldown entries.
    if (currentTime % 1200 == 0) {
      TELEPORT_COOLDOWNS.entrySet().removeIf(e -> currentTime - e.getValue() > COOLDOWN_TICKS * 2);
    }
  }

  /**
   * Extracts link data from a book item.
   */
  private CompoundTag getLinkData(ItemStack book) {
    if (book.isEmpty() || ItemStackNbt.getTag(book) == null) {
      return null;
    }
    if (book.getItem() instanceof LinkbookItem || book.getItem() instanceof AgebookItem) {
      return ItemStackNbt.getTag(book);
    }
    return null;
  }

  /**
   * Locates the controlling receptacle via PortalUtils' BFS — robust against
   * arbitrary frame shapes and reorderings.
   */
  private BookReceptacleBlockEntity findReceptacle(Level level, BlockPos pos) {
    if (PortalUtils.findReceptacle(level, pos) instanceof BookReceptacleBlockEntity receptacle) {
      return receptacle;
    }
    return null;
  }

  @Override
  public void neighborChanged(BlockState state, Level level, BlockPos pos, Block neighborBlock,
                              BlockPos neighborPos, boolean movedByPiston) {
    if (level.isClientSide) return;
    // Only validate when an actual neighbor changes externally (frame block broken,
    // receptacle removed, etc.). Portal creation uses UPDATE_NONE so this is not
    // re-entered during fillPortalBlocks().
    PortalUtils.validatePortal(level, pos);
  }
}
