plugins {
    id 'fabric-loom' version '1.9.2'
}

tasks.named('compileJava') {
    enabled = false
}

tasks.named('classes') {
    enabled = false
}

tasks.named('jar') {
    enabled = false
}

tasks.named('remapJar') {
    enabled = false
}

tasks.named('remapSourcesJar') {
    enabled = false
}

loom {

}

dependencies {

    minecraft "com.mojang:minecraft:${minecraft_version_1_20_1}"
    mappings loom.officialMojangMappings()

    modCompileOnly "net.fabricmc:fabric-loader:${fabric_loader_version_1_20_1}"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version_1_20_1}"

    compileOnly "net.minecraftforge:forge:${minecraft_version_1_20_1}-${forge_version_1_20_1}"

    compileOnly "com.electronwill.night-config:core:3.6.7"
    compileOnly "com.electronwill.night-config:toml:3.6.7"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
