# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = art.arcane.mystcraft
archives_name = mystcraft
mod_id = mystcraft
mod_name = Mystcraft 2 - Pages Unturned
mod_license = LGPLv3
mod_authors = NextdoorPsycho, XCompWiz
mod_description = Mystcraft 2 - Pages Unturned brings the Myst series to modern Minecraft, allowing players to write and travel to custom Ages.
enabled_platforms = fabric,forge,quilt

# Minecraft properties
minecraft_version = 1.20.2

# Dependencies
architectury_api_version = 10.1.20
fabric_loader_version = 0.18.4
fabric_api_version = 0.91.6+1.20.2
forge_version = 1.20.2-48.1.0
quilt_loader_version = 0.30.0-beta.0
quilted_fabric_api_version = 8.0.0-alpha.6+0.91.6-1.20.2
