# Project
version=0.5.0-dev
group=art.arcane.mystcraft
java_version=17
java_version_forge=17
java_version_fabric=17
java_version_neoforge=17

# Common
minecraft_version=1.20.2
mod_name=Mystcraft 2 Legacy - Pages Returned
mod_author=NextdoorPsycho, XCompWiz
mod_id=mystcraft
license=LGPLv3
credits=Originally created by XCompWiz. Ported and maintained by NextdoorPsycho.
description=Mystcraft 2 Legacy - Pages Returned brings the Myst series to Minecraft, allowing players to write and travel to custom Ages (dimensions).
minecraft_version_range=[1.20.2,1.21)

# Fabric
fabric_version=0.91.6+1.20.2
fabric_loader_version=0.18.4

# Forge
forge_version=48.1.0
forge_loader_version_range=[48,)

# NeoForge
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)

# Build Output
# Set this to a custom directory where all built jars should be copied.
# Supports both macOS and Windows paths. Leave empty to skip copying.
# Examples:
#   macOS:   /Users/yourname/mods
#   Windows: C:/Users/yourname/mods
build_output_dir=/Users/brianfopiano/Developer/RemoteGit/NextdoorPsycho/Mystcraft-Legacy-Returned/MystcraftOut

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
